pull_request_rules:
  - name: Automatic merge on label addition
    conditions:
      - label=mergify
      - status-success=pre-commit
      - status-success=clippy
      - status-success~=test \(.*\)
      - status-success~=build \(.*\)
    actions:
      merge:
        method: rebase
        rebase_fallback: null
        strict: smart
  - name: Automatic cleanup on close
    conditions:
      - closed
    actions:
      delete_head_branch: {}
      label:
        remove: [mergify]
