[package]
name = "git-trim"
description = "Automatically trims your tracking branches whose upstream branches are merged or stray"
license = "MIT"
version = "0.4.2"
authors = ["SeongChan Lee <foriequal@gmail.com>"]
repository = "https://github.com/foriequal0/git-trim"
readme = "README.md"
keywords = ["git", "branch", "prune", "trim"]
categories = ["command-line-utilities", "development-tools"]
edition = "2018"
build = "build.rs"
default-run = "git-trim"

[[bin]]
name = "build-man"
required-features = ["build-man"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
build-man = ["man", "rson_rs", "regex"]

[build-dependencies]
vergen = "7.0.0"

[dependencies]
dialoguer = "0.10.0"
env_logger = "0.9.0"
git2 = "0.14.2"
log = "0.4.16"
paw = "1.0.0"
clap = { package = "clap-v3", version = "3.0.0-beta.1" }
anyhow = "1.0.56"
rayon = "1.5.2"
thiserror = "1.0.30"
crossbeam-channel = "0.5.4"
textwrap = { version = "0.15.0", features = ["terminal_size"] }

man = { version = "0.3.0", optional = true }
rson_rs = { version = "0.2.1", optional = true }
regex = { version = "1.5.5", optional = true }

[dev-dependencies]
tempfile = "3.3.0"
